/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traveling;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.sql.DriverManager;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author ASUS
 */
public class harga extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form harga
     */
    public harga() {
        initComponents();
        setDefaultCloseOperation(harga.DO_NOTHING_ON_CLOSE);
        tampildata();
        bersih();
        koneksi();
    }
private void bersih(){
   kode.setText(null); 
   cmbjenis.setSelectedItem(null); 
   nominal.setText(null);
   kode.requestFocus();
    }   
public void getMouseClick(){
        int jTable1 = tbharga.getSelectedRow();
        String a = tbharga.getValueAt(jTable1, 0).toString();
        String b = tbharga.getValueAt(jTable1, 1).toString();
        String c = tbharga.getValueAt(jTable1, 2).toString();
        kode.setText(a);
        cmbjenis.setSelectedItem(b);
        nominal.setText(c);
        kode.setEnabled(false);
}
public void koneksi(){
try{
Class.forName("com.mysql.jdbc.Driver");
con = DriverManager.getConnection("jdbc:mysql://localhost:3306/database","root","");
stat = con.createStatement();
}catch (ClassNotFoundException | SQLException e){
JOptionPane.showMessageDialog(this,"koneksi gagal..",
"Error",JOptionPane.ERROR_MESSAGE);
System.out.println(e.getMessage());
}
}
public void tampildata(){ 
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("KODE HARGA");
tabelnyo.addColumn("JENIS PELAYANAN ");
tabelnyo.addColumn("NOMINAL");
try{
koneksi();
sql = "Select * from harga ORDER BY `Jenis` ASC";
rs = stat.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1), 
rs.getString(2),
rs.getInt(3)
});
}
tbharga.setModel(tabelnyo);
}catch (Exception e)
{
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
 void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom Ini Hanya Bisa Memasukan Karakter Angka");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tcari = new javax.swing.JTextField();
        nominal = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbharga = new javax.swing.JTable();
        cmbjenis = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tcari.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });
        getContentPane().add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 170, 30));

        nominal.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        nominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominalActionPerformed(evt);
            }
        });
        nominal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nominalKeyTyped(evt);
            }
        });
        getContentPane().add(nominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, 30));

        kode.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });
        kode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kodeKeyTyped(evt);
            }
        });
        getContentPane().add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 200, 30));

        tbharga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbharga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbharga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Harga", "Jenis", "Nominal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbharga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhargaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbharga);
        if (tbharga.getColumnModel().getColumnCount() > 0) {
            tbharga.getColumnModel().getColumn(0).setResizable(false);
            tbharga.getColumnModel().getColumn(1).setResizable(false);
            tbharga.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 780, 170));

        cmbjenis.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULER", "VIP", "VVIP" }));
        getContentPane().add(cmbjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 200, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 100, -1));

        batal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 80, -1));

        hapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 80, -1));

        ubah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 80, -1));

        kembali.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        logout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 80, -1));

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton7.setText("Cetak Laporan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 140, -1));

        simpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 80, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Jenis");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Nominal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Kode Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 130, 30));

        jLabel1.setFont(new java.awt.Font("Stencil Std", 1, 40)); // NOI18N
        jLabel1.setText("Daftar harga");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 340, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Screenshot (434).jpg"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 920, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void tbhargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbhargaMouseClicked
getMouseClick();        // TODO add your handling code here:
    }//GEN-LAST:event_tbhargaMouseClicked

    private void nominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nominalActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
     kode.setEnabled(true);
     login mnu = new login();
     mnu.setVisible(true);
     dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
    kode.setEnabled(true);
    menu_utama mnu = new menu_utama();
    mnu.setVisible(true);
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
  if(kode.getText().equals("")||cmbjenis.getSelectedItem().equals("PILIH")||nominal.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Data tidak boleh kosong");
  } else {    
      try {
      koneksi();
      sql = "INSERT INTO harga VALUES ('"+kode.getText()+"','"+cmbjenis.getSelectedItem()+"','"+nominal.getText()+"')";
      stat.executeUpdate(sql);
      con.close();
      tampildata();
      bersih();
      JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
      } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Gagal");
     }
  }        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
if(kode.getText().equals("")||cmbjenis.getSelectedItem().equals("PILIH")||nominal.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Data tidak boleh kosong");
  } else { 
    try{
    koneksi();
    sql = "UPDATE `harga` SET `Jenis`='"+cmbjenis.getSelectedItem()+"',`Nominal`='"+nominal.getText()+"' WHERE `Kode Harga`='"+kode.getText()+"'";
    stat.executeUpdate(sql);
      con.close();
      tampildata();
      bersih();
      kode.setEnabled(true);
      JOptionPane.showMessageDialog(null, "Pengubahan Data Berhasil");
      } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Gagal");
     }
} // TODO add your handling code here:
    }//GEN-LAST:event_ubahActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
bersih();
kode.setEnabled(true);
tcari.setText("");
tampildata();        // TODO add your handling code here:
    }//GEN-LAST:event_batalActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
 if(kode.getText().equals("")||cmbjenis.getSelectedItem().equals("PILIH")||nominal.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Data tidak boleh kosong");
  } else { 
     try{
        koneksi();
        sql = "DELETE FROM `harga` WHERE `Kode harga`='"+kode.getText()+"'";
        stat.executeUpdate(sql);
        con.close();
        JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
        tampildata();
        bersih();
        kode.setEnabled(true);
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal..");
        System.out.println(e.getMessage());
    }
}// TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(tcari.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Data tidak boleh kosong");
  } else {    
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("KODE HARGA");
tabelnyo.addColumn("JENIS PELAYANAN");
tabelnyo.addColumn("NOMINAL");
try{
koneksi();
sql = "Select * from `harga` where `Kode Harga` like '%"+tcari.getText()+"%'"+"or `Jenis` like '%"+tcari.getText() +"%'";
rs = stat.executeQuery(sql);
while (rs.next()) {
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3)});
}
tbharga.setModel(tabelnyo);
}catch (SQLException e){
} 
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeKeyTyped
filterhuruf(evt);
if (kode.getText().length() == 3 ) {
        evt.consume(); 
        }// TODO add your handling code here:
    }//GEN-LAST:event_kodeKeyTyped

    private void nominalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nominalKeyTyped
filterhuruf(evt);
if (nominal.getText().length() == 20 ) {
        evt.consume(); 
        }// TODO add your handling code here:
    }//GEN-LAST:event_nominalKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 try {
     HashMap parameter = new HashMap();
     koneksi();
     File file = new File("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Traveling\\src\\methodprint\\harga.jasper");
     JasperReport jr = (JasperReport) JRLoader.loadObject(file);
     JasperPrint jp = JasperFillManager.fillReport(jr, parameter,con);
     JasperViewer.viewReport(jp, false);
     JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(harga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(harga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(harga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(harga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new harga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JComboBox<String> cmbjenis;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField kode;
    private javax.swing.JButton logout;
    private javax.swing.JTextField nominal;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tbharga;
    private javax.swing.JTextField tcari;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
