/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traveling;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.sql.DriverManager;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author ASUS
 */
public class penumpang extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form penumpang
     */
    public penumpang() {
        initComponents();
        tampildata();
        bersih();
        koneksi();
        setDefaultCloseOperation(penumpang.DO_NOTHING_ON_CLOSE);
    }
    private void bersih(){
   kode.setText(null); 
   nama.setText(null);
   identitas.setText(null);
   cmbjk.setSelectedItem(null); 
   usia.setText(null);
   telepon.setText(null);
   alamat.setText(null);
   kode.requestFocus();
    }   
public void getMouseClick(){
        int jTable1 = tbpenumpang.getSelectedRow();
        String a = tbpenumpang.getValueAt(jTable1, 0).toString();
        String b = tbpenumpang.getValueAt(jTable1, 1).toString();
        String c = tbpenumpang.getValueAt(jTable1, 2).toString();
        String d = tbpenumpang.getValueAt(jTable1, 3).toString();
        String e = tbpenumpang.getValueAt(jTable1, 4).toString();
        String f = tbpenumpang.getValueAt(jTable1, 5).toString();
        String g = tbpenumpang.getValueAt(jTable1, 6).toString();
        
        kode.setText(a);
        cmbjk.setSelectedItem(d);
        nama.setText(b);
        identitas.setText(c);
        usia.setText(e);
        telepon.setText(f);
        alamat.setText(g);
        kode.setEnabled(false);
}
public void koneksi(){
try{
Class.forName("com.mysql.jdbc.Driver");
con = DriverManager.getConnection("jdbc:mysql://localhost:3306/database","root","");
stat = con.createStatement();
}catch (ClassNotFoundException | SQLException e){
JOptionPane.showMessageDialog(this,"koneksi gagal..",
"Error",JOptionPane.ERROR_MESSAGE);
System.out.println(e.getMessage());
}
}
public void tampildata(){ 
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("KODE");
tabelnyo.addColumn("NAMA ");
tabelnyo.addColumn("NO.IDENTITAS");
tabelnyo.addColumn("JENIS KELAMIN");
tabelnyo.addColumn("USIA");
tabelnyo.addColumn("TELEPON");
tabelnyo.addColumn("ALAMAT");
try{
koneksi();
sql = "SELECT * FROM `penumpang`ORDER BY `nama` ASC";
rs = stat.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1), 
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getInt(5),
rs.getString(6),
rs.getString(7)
});
}
tbpenumpang.setModel(tabelnyo);
}catch (Exception e)
{
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
 void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom Ini Hanya Bisa Memasukan Karakter Angka");
        }
    }
 void filterangka(KeyEvent b){
        if(Character.isDigit(b.getKeyChar())){
            b.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom Ini Hanya Bisa Memasukan Karakter Huruf");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        identitas = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        telepon = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        cmbjk = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpenumpang = new javax.swing.JTable();
        cari = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel7.setText("Usia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setText("No. Identitas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 140, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel8.setText("Telepon");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 140, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel9.setText("Alamat");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setText("Kode");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 30));

        jLabel1.setFont(new java.awt.Font("Stencil Std", 1, 40)); // NOI18N
        jLabel1.setText("Data penumpang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 390, 80));

        tcari.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });
        getContentPane().add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 170, -1));

        nama.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaKeyTyped(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 200, 30));

        identitas.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        identitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identitasActionPerformed(evt);
            }
        });
        identitas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                identitasKeyTyped(evt);
            }
        });
        getContentPane().add(identitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 200, 30));

        usia.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        usia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usiaActionPerformed(evt);
            }
        });
        usia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usiaKeyTyped(evt);
            }
        });
        getContentPane().add(usia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 200, 30));

        telepon.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleponActionPerformed(evt);
            }
        });
        telepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teleponKeyTyped(evt);
            }
        });
        getContentPane().add(telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 200, 30));

        alamat.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alamatKeyTyped(evt);
            }
        });
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 560, 40));

        kode.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });
        kode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kodeKeyTyped(evt);
            }
        });
        getContentPane().add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 200, 30));

        cmbjk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        getContentPane().add(cmbjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 200, 30));

        tbpenumpang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbpenumpang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Jadwal", "Asal", "Tujuan", "Tanggal", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbpenumpang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpenumpangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpenumpang);
        if (tbpenumpang.getColumnModel().getColumnCount() > 0) {
            tbpenumpang.getColumnModel().getColumn(0).setResizable(false);
            tbpenumpang.getColumnModel().getColumn(1).setResizable(false);
            tbpenumpang.getColumnModel().getColumn(2).setResizable(false);
            tbpenumpang.getColumnModel().getColumn(3).setResizable(false);
            tbpenumpang.getColumnModel().getColumn(4).setResizable(false);
            tbpenumpang.getColumnModel().getColumn(5).setResizable(false);
            tbpenumpang.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 780, 120));

        cari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 80, -1));

        batal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 80, -1));

        hapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 80, -1));

        ubah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 80, -1));

        kembali.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        logout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 80, -1));

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton7.setText("Cetak Laporan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 140, -1));

        simpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 80, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Screenshot (434).jpg"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 920, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void tbpenumpangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpenumpangMouseClicked
getMouseClick();        // TODO add your handling code here:
    }//GEN-LAST:event_tbpenumpangMouseClicked

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void identitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identitasActionPerformed

    private void usiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usiaActionPerformed

    private void teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teleponActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
  if(kode.getText().equals("")||nama.getText().equals("")||identitas.getText().equals("")||cmbjk.getSelectedItem().equals("")||
          usia.getText().equals("")||telepon.getText().equals("")||alamat.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Data tidak boleh kosong");
  } else {    
      try {
      koneksi();
      sql = "INSERT INTO `penumpang` VALUES ('"+kode.getText()+"','"+nama.getText()+"','"+identitas.getText()+"','"+cmbjk.getSelectedItem()+"',"+ "'"+usia.getText()+"','"+telepon.getText()+"','"+alamat.getText()+"')";
      stat.executeUpdate(sql);
      con.close();
      tampildata();
      bersih();
      JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
      } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Gagal");
     }
  }        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
  if(kode.getText().equals("")||nama.getText().equals("")||identitas.getText().equals("")||cmbjk.getSelectedItem().equals("")||
          usia.getText().equals("")||telepon.getText().equals("")||alamat.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Data tidak boleh kosong");
  } else { 
      try{
    koneksi();
    sql = "UPDATE `penumpang` SET `nama`='"+nama.getText()+"',`identitas`='"+identitas.getText()+"',`jenis kelamin`='"+cmbjk.getSelectedItem()+"',`usia`='"+usia.getText()+"',`telepon`='"+telepon.getText()+"',`alamat`='"+alamat.getText()+"' WHERE `kode`='"+kode.getText()+"'";
    stat.executeUpdate(sql);
      con.close();
      tampildata();
      bersih();
      kode.setEnabled(true);
      JOptionPane.showMessageDialog(null, "Pengubahan Data Berhasil");
      } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Gagal");
     }
}// TODO add your handling code here:
    }//GEN-LAST:event_ubahActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
bersih();
kode.setEnabled(true);
tcari.setText(null);
tampildata();           // TODO add your handling code here:
    }//GEN-LAST:event_batalActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
if(kode.getText().equals("")||nama.getText().equals("")||identitas.getText().equals("")||cmbjk.getSelectedItem().equals("")||
          usia.getText().equals("")||telepon.getText().equals("")||alamat.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Data tidak boleh kosong");
  } else {
    try{
    koneksi();
        sql = "DELETE FROM `penumpang` WHERE `kode`='"+kode.getText()+"'";
        stat.executeUpdate(sql);
        con.close();
        JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
        tampildata();
        bersih();
        kode.setEnabled(true);
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal..");
        System.out.println(e.getMessage());
    }
}// TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
if(tcari.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Data tidak boleh kosong");
  } else { 
    DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("KODE PENUMPANG");
tabelnyo.addColumn("NAMA ");
tabelnyo.addColumn("NO.IDENTITAS");
tabelnyo.addColumn("JENIS KELAMIN");
tabelnyo.addColumn("USIA");
tabelnyo.addColumn("TELEPON");
tabelnyo.addColumn("ALAMAT");
try{
koneksi();
sql = "Select * from `penumpang` where `kode` like '%"+tcari.getText()+"%'"+"or `nama` like '%"+tcari.getText() +"%'"+"or `identitas` like '%"+tcari.getText() +"%'";
rs = stat.executeQuery(sql);
while (rs.next()) {
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7)
});
}
tbpenumpang.setModel(tabelnyo);
}catch (SQLException e){
} 
}  // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
    kode.setEnabled(true);
    menu_utama mnu = new menu_utama();
    mnu.setVisible(true);
    dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
     kode.setEnabled(true);
     login mnu = new login();
     mnu.setVisible(true);
     dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void kodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeKeyTyped
filterhuruf(evt);
if (kode.getText().length() == 3 ) {
        evt.consume(); 
        }
    }//GEN-LAST:event_kodeKeyTyped

    private void namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyTyped
filterangka(evt);
if (nama.getText().length() == 30 ) {
        evt.consume(); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_namaKeyTyped

    private void identitasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identitasKeyTyped
filterhuruf(evt);
if (identitas.getText().length() == 24 ) {
        evt.consume(); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_identitasKeyTyped

    private void usiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usiaKeyTyped
filterhuruf(evt);
if (usia.getText().length() == 3 ) {
        evt.consume(); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_usiaKeyTyped

    private void teleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teleponKeyTyped
filterhuruf(evt);
if (telepon.getText().length() == 15 ) {
        evt.consume(); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_teleponKeyTyped

    private void alamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamatKeyTyped
if (alamat.getText().length() == 100 ) {
        evt.consume(); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_alamatKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 try {
     HashMap parameter = new HashMap();
     koneksi();
     File file = new File("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Traveling\\src\\methodprint\\penumpang.jasper");
     JasperReport jr = (JasperReport) JRLoader.loadObject(file);
     JasperPrint jp = JasperFillManager.fillReport(jr, parameter,con);
     JasperViewer.viewReport(jp, false);
     JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penumpang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton batal;
    private javax.swing.JButton cari;
    private javax.swing.JComboBox<String> cmbjk;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField identitas;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField kode;
    private javax.swing.JButton logout;
    private javax.swing.JTextField nama;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tbpenumpang;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField telepon;
    private javax.swing.JButton ubah;
    private javax.swing.JTextField usia;
    // End of variables declaration//GEN-END:variables
}
